### ISSUE TITLE
Veste Coburg Model Integration and Visualization

### ISSUE THREAD

**Issue by Masihtabaei** [Masihtabaei/3d-visualization-project#8]

**Comment by MacRosefield** [comment]
# Dokumentation: Umstellung von Emission Shader auf BSDF Shader in Blender

## Ausgangssituation
In der ursprünglichen Szene wurden Materialien verwendet, die den **Emission Shader** als Hauptshader enthielten. Dieser Shader war möglicherweise mit Texturen (z. B. für Farbe oder Stärke) verbunden, um das Erscheinungsbild des Materials zu definieren. Ziel war es, alle **Emission Shader** durch den universellen **Principled BSDF Shader** zu ersetzen, ohne bestehende Texturen oder Verbindungen zu verlieren.

---

## Vorgehensweise

### 1. Identifikation der Materialien
- Alle Materialien in der Szene wurden durchlaufen.
- Es wurde geprüft, ob das Material **Nodes** verwendet. Falls nicht, wurde das Material übersprungen.

### 2. Ersetzen des Emission Shaders
- Der **Emission Shader** wurde in jedem Material lokalisiert.
- Sein Standort im Node Editor wurde gespeichert, um den neuen **Principled BSDF Shader** an der gleichen Stelle einzufügen.

### 3. Übertragung der Verbindungen
- **Eingänge des Emission Shaders:** 
  - Die **Color-Input-Verbindung** des Emission Shaders wurde auf den **Base Color** des BSDF Shaders übertragen.
  - Die **Strength-Input-Verbindung** wurde auf die **Emission Strength** des BSDF Shaders übertragen.
- **Ausgänge des Emission Shaders:** 
  - Verbindungen zu den Material-Output-Nodes wurden gesichert und mit dem BSDF Shader neu verbunden.

### 4. Entfernen des Emission Shaders
- Nachdem der neue BSDF Shader eingefügt und alle Verbindungen aktualisiert wurden, wurde der alte **Emission Shader** aus dem Material entfernt.

---

## Endergebnis
Nach dem Ausführen des Skripts wurden alle **Emission Shader** durch **Principled BSDF Shader** ersetzt. Verbindungen zu Texturen und anderen Nodes wurden beibehalten und auf die entsprechenden Eingänge des neuen Shaders übertragen. Die Materialien sind jetzt flexibler und physikalisch realistischer gestaltet.

---

## Vorteile der Anpassung
- **Kompatibilität:** Der **Principled BSDF Shader** ist standardisiert und unterstützt komplexere Materialeigenschaften.
- **Realismus:** Durch die Verwendung eines BSDF Shaders können Materialien Licht realistischer reflektieren und brechen.
- **Zukunftssicherheit:** Der **Principled BSDF Shader** ist vielseitiger und besser für moderne Rendering-Engines geeignet.

---

## Skript
Das verwendete Python-Skript ist modular aufgebaut und kann für ähnliche Anpassungen an Materialien wiederverwendet werden. Es stellt sicher, dass die ursprünglichen Verbindungen erhalten bleiben und das Materialverhalten konsistent bleibt.
